# Generated by Django 3.1.2 on 2022-12-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElderlyApp', '0005_remove_userdata_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='born',
            new_name='date_born',
        ),
    ]
