# Generated by Django 3.1.2 on 2022-12-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElderlyApp', '0009_auto_20221210_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='text_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='title_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
