# Generated by Django 3.1.2 on 2022-12-10 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElderlyApp', '0010_auto_20221210_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='surname',
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='accept_button_colors',
            field=models.CharField(default='#008800', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='decline_button_colors',
            field=models.CharField(default='#ff0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='text_size',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='title_size',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
